// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaHQ5fpmYqsjET-Pdzh0zdh6UE2UQGGUA',
    appId: '1:572475259854:web:0d17262505d5b2b6aa099f',
    messagingSenderId: '572475259854',
    projectId: 'styleme-e47c1',
    authDomain: 'styleme-e47c1.firebaseapp.com',
    storageBucket: 'styleme-e47c1.appspot.com',
    measurementId: 'G-02H4QYD3NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtkN-b31QyW8fSW1Q5PKGgDNi65PYJS9A',
    appId: '1:572475259854:android:88187bead2fcb413aa099f',
    messagingSenderId: '572475259854',
    projectId: 'styleme-e47c1',
    storageBucket: 'styleme-e47c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHZywNdIOh3O-KbUO2plO_v9LBe0SuDRQ',
    appId: '1:572475259854:ios:85f1ed17386fa75faa099f',
    messagingSenderId: '572475259854',
    projectId: 'styleme-e47c1',
    storageBucket: 'styleme-e47c1.appspot.com',
    iosBundleId: 'com.example.styleMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHZywNdIOh3O-KbUO2plO_v9LBe0SuDRQ',
    appId: '1:572475259854:ios:60d56cd7a74cf172aa099f',
    messagingSenderId: '572475259854',
    projectId: 'styleme-e47c1',
    storageBucket: 'styleme-e47c1.appspot.com',
    iosBundleId: 'com.example.styleMe.RunnerTests',
  );
}
